sudo: required
services:
  - docker

ิิbefore_install:
  - docker build -t kantapong/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kantapong/client-test npm run test

after_success:
  - docker build -t kantapong/multi-client ./client
  - docker build -t kantapong/multi-nginx ./nginx
  - docker build -t kantapong/multi-server ./server
  - docker build -t kantapong/multi-worker ./worker
  #  Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kantapong/multi-client
  - docker push kantapong/multi-nginx
  - docker push kantapong/multi-server
  - docker push kantapong/multi-worker
