sudo: required
services:
  - docker

ิิbefore_install:
  - docker build -t kantapong24/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kantapong24/client-test npm run test

after_success:
  - docker build -t kantapong24/multi-client ./client
  - docker build -t kantapong24/multi-nginx ./nginx
  - docker build -t kantapong24/multi-server ./server
  - docker build -t kantapong24/multi-worker ./worker
  #  Login to the docker CLI test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kantapong24/multi-client
  - docker push kantapong24/multi-nginx
  - docker push kantapong24/multi-server
  - docker push kantapong24/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "ap-southeast-2"
#   app: "multi-docker"
#   env: "Multi-docker"
#   bucket_name: "elasticbeanstalk-ap-southeast-2-536940935569"
#   bucket_path: "docker-multi"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
